src/flask/flasky/app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin, AnonymousUserMixin
from . import login_manager
from itsdangerous import URLSafeTimedSerializer as Serializer
from flask import current_app
from datetime import datetime


@login_manager.user_loader  # zarejestrowanie funkcji w Flask-Login, które ją wywoła w chwili potrzeby pobrania info o user
def load_user(user_id):
    return User.query.get(int(user_id))


class Permission:
    FOLLOW = 1
    COMMENT = 2
    WRITE = 4
    MODERATE = 8
    ADMIN = 16


class Role(db.Model):
    __tablename__ = "roles"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    users = db.relationship("User", backref="role", lazy="dynamic")
    default = db.Column(db.Boolean, default=False, index=True)
    permission = db.Column(db.Integer)

    def __init__(self, **kwargs):
        super(Role, self).__init__(**kwargs)
        if self.permission is None:
            self.permission = 0

    def has_permission(self, perm):
        return self.permission & perm == perm

    def add_permission(self, perm):
        if not self.has_permission(perm):
            self.permission += perm

    def remove_permission(self, perm):
        if self.has_permission(perm):
            self.permission -= perm

    def reset_permission(self):
        self.permission = 0

    def __repr__(self):
        return str(self.name)

    @staticmethod
    def insert_roles():
        roles = {"User": [Permission.FOLLOW,
                          Permission.COMMENT,
                          Permission.WRITE],
                 "Administrator": [Permission.FOLLOW,
                                   Permission.COMMENT,
                                   Permission.WRITE,
                                   Permission.MODERATE,
                                   Permission.ADMIN],
                 "Moderator": [Permission.FOLLOW,
                               Permission.COMMENT,
                               Permission.WRITE,
                               Permission.MODERATE]}
        default_role = 'User'
        for _role, _permissions_list in roles.items():
            role = Role.query.filter_by(name=_role).first()
            if role is None:
                role = Role(name=_role)
            for permission in _permissions_list:
                role.add_permission(permission)
            role.default = (role.name == default_role)
            db.session.add(role)
        db.session.commit()


class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    priorytet = db.Column(db.Integer())
    email = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    confirmed = db.Column(db.Boolean, default=False)
    location = db.Column(db.String(64))
    about_me = db.Column(db.Text())
    member_since = db.Column(db.DateTime(), default=datetime.utcnow)
    last_seen = db.Column(db.DateTime(), default=datetime.utcnow)
    role_id = db.Column(db.Integer, db.ForeignKey("roles.id"))

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config["MAIL_SENDER"]:
                self.role = Role.query.filter_by(name="Administrator").first()
            if self.role is None:
                self.role = Role.query.filter_by(default=True).first()

    def can(self, permission):
        return self.role is not None and self.role.has_permission(permission)
    
    def is_administrator(self):
        return self.can(Permission.ADMIN)

    @property
    def password(self):
        raise AttributeError("Odczyt hasla zabroniony")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def password_verify(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self):
        serial = Serializer(current_app.config["SECRET_KEY"])
        return serial.dumps({"confirm": self.id}).encode("utf-8")

    def confirm_token(self, token):
        serial = Serializer(current_app.config["SECRET_KEY"])
        try:
            data = serial.loads(token.encode("utf-8"))
        except Exception as e:
            print(f"Problem with getting token {e}")
            return False
        if data.get("confirm") != self.id:
            print("Problem with token confirmation")
            return False
        self.confirmed = True
        db.session.add(self)
        return True

    def ping(self):
        self.last_seen = datetime.utcnow()
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return str(self.username)


class AnonymousUser(AnonymousUserMixin):
    def can(self, permission):
        return False

    def is_administrator(self):
        return False

login_manager.anonymous_user = AnonymousUser

src/flask/flasky/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, EmailField, BooleanField, widgets
from wtforms.validators import DataRequired


class MojaForma(FlaskForm):
    name = StringField("Jak masz na imię?", default=None, validators=[DataRequired()])
    priorytet_minimum = 0
    priorytet_maximum = 10
    priorytet = IntegerField(f"Priorytet ({priorytet_minimum} do {priorytet_maximum})", default=0,
                             widget=widgets.NumberInput(min=priorytet_minimum, max=priorytet_maximum))
    wyslij_email = BooleanField(default=False)
    email = EmailField("Email")
    submit = SubmitField("Wyslij")

src/flask/flasky/app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from src.flask.flasky.config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.login_view = "auth.login"


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix="/auth")  # prefix zmienia /login na /auth/login

    return app

src/flask/flasky/app/main/__init__.py
from flask import Blueprint

main = Blueprint("main", __name__)

from . import views, errors
from ..models import Permission


@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

src/flask/flasky/app/main/views.py
from . import main
from ..models import User
from .forms import MojaForma
from .. import db
from flask import render_template, session, redirect, url_for, flash
import datetime
from ..email import send_email_message


@main.route("/", methods=["GET", "POST"])
def index():
    moja_forma = MojaForma()
    if moja_forma.validate_on_submit():
        name_from_db = User.query.filter_by(username=moja_forma.name.data).first()
        if name_from_db:
            flash(f"Uzytkownik {name_from_db.username} już istnieje.")
        else:
            # Dodanie do bazy danych
            user = User(email=moja_forma.email.data,
                        username=moja_forma.name.data.lower(),
                        priorytet=moja_forma.priorytet.data)
            db.session.add(user)
            db.session.commit()
            # Dodanie do cookies
            session["name"] = moja_forma.name.data
            session["priorytet"] = moja_forma.priorytet.data
            session["email"] = moja_forma.email.data
            if moja_forma.wyslij_email.data:
                send_email_message("Witamy na stronie Flasky", ["anana900@wp.pl"],
                                   "mail/email",  user=moja_forma.name.data,
                                   timestamp=datetime.datetime.now())
                flash(f"SUCCESS Wyslano email")
        # tutaj robimy przekierowanie zapobiegające ponownemy wysłaniu formularza w przypadku odświeżenia
        return redirect(url_for("main.index"))
    return render_template("index.html", current_time=datetime.datetime.utcnow(),
                           moja_forma=moja_forma, name=session.get("name"), priorytet=session.get("priorytet"),
                           email=session.get("email"))


@main.route("/user/<username>")
def user(username):
    usr = User.query.filter_by(username=username).first_or_404()
    return render_template('user.html', user=usr)

src/flask/flasky/app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "makra.html" as makra %}


{% block scripts %}
{{ super() }}
<!-- Importowanie biblioteki Moment.js -->
{{ moment.include_moment() }}
<!-- Set LANGUAGE -->
{{ moment.locale('pl') }}
{% endblock %}


{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='mbot.png') }}" type="image/png">
<link rel="icon" href="{{ url_for('static', filename='bot.png') }}" type="image/png">
{% endblock %}

{% block title %}Flasky{% endblock %}
{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
            data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Przełącz pasek nawigacji</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Flasky</a>
        </div>
        <div class="navbar-collapse collapse">

            <ul class="nav navbar-nav">
                <li><a href="/">Strona główna</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                {% else %}
                    <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}

                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profil</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="container">

    <!-- Obsługa komunikatów POPUP typu flash -->
    {% for message in get_flashed_messages() %}
        {% if "SUCCESS" in message %}
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>{{ message }}
            </div>
        {% else %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>{{ message }}
            </div>
        {% endif %}
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

src/flask/flasky/app/templates/index.html
{% extends "base.html" %}

{% block title %}Flasky{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Hello, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>
    <p>Aktualny czas {{ moment(current_time).format("LLL") }}</p>
    <p>To było {{ moment(current_time).fromNow(refresh=True) }}</p>
    <p>{{ moment(current_time).calendar() }}</p>
</div>
{% endblock %}

src/flask/flasky/app/templates/makra.html
<!-- Tworzenie elementu listy -->
{% macro lista_element(element) %}
    <li>{{ element }}</li>
{% endmacro %}

<!-- Tworzenie prostej listy -->
{% macro lista_prosta(elementy) %}
<ul>
    {% for element in elementy %}
        {{ lista_element(element) }}
    {% endfor %}
</ul>
{% endmacro %}

src/flask/flasky/app/templates/user.html
{% extends "base.html" %}
{% block title %}Flasky{% endblock %}
{% block page_content %}
<div class="page-header">
    <h1>{{ user.username }}</h1>
    {% if user.name or user.location %}
    <p>
        {% if user.name %}{{ user.name }}{% endif %}
        {% if user.location %}
            From <a href="http://maps.google.com/?q={{ user.location }}">
                {{ user.location }}
            </a>
        {% endif %}
    </p>
    {% endif %}
    {% if current_user.is_administrator() %}
    <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
    {% endif %}
    {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
    <p>
        Data rejestracji {{ moment(user.member_since).format('L') }}.
        Ostatnia aktywność {{ moment(user.last_seen).fromNow() }}.
    </p>
</div>
{% endblock %}